Added portal shortcut

diff --git a/install/bash_aliases b/install/bash_aliases
--- a/install/bash_aliases
+++ b/install/bash_aliases
@@ -8,9 +8,15 @@ GREEN=$(tput setaf 10)
 RESET_HL=$(tput sgr0) ## reset all text formatting
 
 # print help
-commands() {
+commands() (
+	cd "$HYPERNETS_TOOLS"
+
 	dupcc=$(df -kh . | tail -n1 | awk '{print $5}') >/dev/null 2>&1
 	duchk="${dupcc//%}"
+
+	source utils/configparser.sh
+	ipServer=$(parse_config "credentials" config_static.ini)
+	remoteDir=$(parse_config "remote_dir" config_static.ini)
 
 	echo
 	if [[ "$duchk" -ge 80 ]]
@@ -32,7 +38,7 @@ commands() {
 	echo "${HL} status  	${RESET_HL}sudo systemctl status hypernets-sequence"
 	echo "${HL} kill-service	${RESET_HL}kill hypernets-sequence service without going to sleep"
 	echo "${HL} journal  	${RESET_HL}journalctl -b -u hypernets-sequence -e (journal -f to follow)"
-	#echo "${HL} portal  	${RESET_HL}makes a portal via ~/Portal folder to Server/Sitename/ "
+	echo "${HL} portal  	${RESET_HL}makes a portal via ~/Portal folder to $ipServer/${remoteDir%/}/"
 	echo "${HL} gui		${RESET_HL}python -m hypernets.gui (if screen attached)"
 	echo "${HL} webpic 	${RESET_HL}take webcam photo    webpic -h for help"
 	echo "${HL} hypypic  	${RESET_HL}take photo from hypstar camera"
@@ -41,7 +47,7 @@ commands() {
 	echo "${HL} yapo		${RESET_HL}yocto auto-power-off. yapo stop to disable, yapo -h for help"
 	echo "${HL} goto-sleep	${RESET_HL}power off and send yocto to sleep if wakeup is scheduled"
 	echo
-} # commands()
+) # commands()
 
 
 # present status of: clock, meteo, rain, GPS, supply, wakeup
@@ -1446,7 +1452,7 @@ webpic() (
 		if [[ $? -ne 0 ]]; then
 			echo "${XHL}Copying the image to $ipServer failed${RESET_HL}"
 		else
-			echo "${HL}Copied the image to $ipServer:$remoteDir/$cap_file${RESET_HL}"
+			echo "${HL}Copied the image to $ipServer:${remoteDir%/}/$cap_file${RESET_HL}"
 		fi
 	fi
 ) # webpic()
@@ -1455,17 +1461,12 @@ webpic() (
 hypypic()(
 	cd "$HYPERNETS_TOOLS"
 
-	set +e
-
 	OUTPUT_DIR="OTHER/HYPYCAM"
 	mkdir -p "$OUTPUT_DIR"
 	cap_file="$OUTPUT_DIR/$(date -u '+%Y%m%dT%H%M%S').jpg"
 
     set +e
     set pipefail
-#    cap_out=$(utils/webcam_get_image.sh -c "$webcam_credent" -i "$webcam_ip" -d "OTHER/WEBCAM_${cam^^}/" 2>&1 | tee /dev/fd/2)
-#    cap_retcode=$?
-
 	cap_out=$(python -m  hypernets.hypstar.handler -p -b 3000000 -l INFO -d INFO -o "$cap_file" 2>&1 | tee /dev/fd/2)
 	cap_retcode=$?
 
@@ -1491,10 +1492,37 @@ hypypic()(
 		if [[ $? -ne 0 ]]; then
 			echo "${XHL}Copying the image to $ipServer failed${RESET_HL}"
 		else
-			echo "${HL}Copied the image to $ipServer:$remoteDir/$saved_to${RESET_HL}"
+			echo "${HL}Copied the image to $ipServer:${remoteDir%/}/$saved_to${RESET_HL}"
 		fi
 	fi
 ) # hypypic()
+
+
+portal()(
+	cd "$HYPERNETS_TOOLS"
+
+	mkdir -p ~/Portal
+
+	source utils/configparser.sh
+	ipServer=$(parse_config "credentials" config_static.ini)
+	remoteDir=$(parse_config "remote_dir" config_static.ini)
+	sshPort=$(parse_config "ssh_port" config_static.ini)
+	
+	if mountpoint -q ~/Portal; then
+		echo "${HL}Portal is already open${RESET_HL}"
+		exit
+	fi
+
+	set +e
+	echo "${HL}$(readlink -m ~/Portal)/ ---> linking to: ---> $ipServer:${remoteDir%/}/${RESET_HL}"
+	sshfs -p $sshPort "$ipServer:${remoteDir%/}/" ~/Portal
+
+	if [[ $? -eq 0 ]]; then
+		echo "${HL}Portal is open${RESET_HL}"
+	else
+		echo "${XHL}Failed to open Portal${RESET_HL}"
+	fi
+) # portal()
 
 alias kill-service="sudo systemctl kill --signal=SIGKILL hypernets-sequence"
 alias journal="journalctl -b -u hypernets-sequence -e"
